
### 
POST https://localhost:10000/api/v1/snapshots
Content-Type: application/json

{
    "signalSourceId": "TV-DEMO-LONG",
    "time": "2024-01-01T00:00:00",
    "symbol": "BTCUSDT",

    "barTime": "2024-01-01T00:00:00",
    "lastPrice": 1,
    
    "positionSide": "Flat",
    "positionEntryPrice": 1,
    "positionQuantity": 1,
    "positionEntryTime": "2024-01-01T00:00:00",
    "orderQuantity": 1,
    "orderPrice": 0,
    "orderType": "Market",
    "orderTradeType": "Buy",
    "positionEntryComment": ""
}

